// src/pages/PrivacyPolicy.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import AnimatedPageHeader from '../components/common/AnimatedPageHeader';
import PolicyHeaderImage from '../assets/images/about/bg12.jpg'; // Use an appropriate image

const PrivacyPolicy = () => {
  return (
    <div className="bg-white">
      {/* Header */}
      <AnimatedPageHeader 
        title="Privacy Policy" 
        subtitle="Information about how we collect, use, and protect your data"
        backgroundImage={PolicyHeaderImage}
      />

      {/* Content */}
      <section className="py-12 md:py-16 lg:py-20 bg-white">
        <div className="container mx-auto px-4 md:px-6 max-w-4xl">
          <div className="prose prose-lg max-w-none">
            {/* Last updated date */}
            <p className="text-gray-500">Last updated: April 07, 2025</p>
            
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <h2 className="text-2xl md:text-3xl font-serif my-6">Interpretation and Definitions</h2>
            
            <h3 className="text-xl md:text-2xl font-serif my-4">Interpretation</h3>
            
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <h3 className="text-xl md:text-2xl font-serif my-4">Definitions</h3>
            
            <p>For the purposes of this Privacy Policy:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              </li>
              <li>
                <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              </li>
              <li>
                <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HARRICO CEYLON GEMS & JEWELLERY SDN. BHD., No.5.Level 41. Intermark Building 348.Jalan Tun Razak 50400 Kuala Lumpur W.P. Kuala Lumpur Malaysia.</p>
              </li>
              <li>
                <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              </li>
              <li>
                <p><strong>Country</strong> refers to: Malaysia</p>
              </li>
              <li>
                <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
              </li>
              <li>
                <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
              </li>
              <li>
                <p><strong>Service</strong> refers to the Website.</p>
              </li>
              <li>
                <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
              </li>
              <li>
                <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              </li>
              <li>
                <p><strong>Website</strong> refers to Harrico Ceylon Gems & Jewelry, accessible from <a href="https://harricogems.com/" className="text-[#b9a16b] hover:underline" target="_blank" rel="noreferrer">https://harricogems.com/</a></p>
              </li>
              <li>
                <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
              </li>
            </ul>
            
            <h2 className="text-2xl md:text-3xl font-serif my-6">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl md:text-2xl font-serif my-4">Types of Data Collected</h3>
            
            <h4 className="text-lg md:text-xl font-serif my-3">Personal Data</h4>
            
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>
            
            <h4 className="text-lg md:text-xl font-serif my-3">Usage Data</h4>
            
            <p>Usage Data is collected automatically when using the Service.</p>
            
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            
            <h4 className="text-lg md:text-xl font-serif my-3">Tracking Technologies and Cookies</h4>
            
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            
            {/* Continue with the rest of the Privacy Policy content */}
            {/* This is truncated for brevity in this example, but you would include the entire privacy policy */}
            
            {/* Additional sections would go here */}
            
            <h2 className="text-2xl md:text-3xl font-serif my-6">Contact Us</h2>
            
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <p>By email: harricoceylongems@gmail.com</p>
              </li>
              <li>
                <p>By visiting this page on our website: <Link to="/contact" className="text-[#b9a16b] hover:underline">Contact Page</Link></p>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PrivacyPolicy;